language: rust
dist: bionic
osx_image: xcode11
cache: cargo

notifications:
  email: false

addons:
  apt:
    update: true
    packages:
      - libxcb1-dev
      - libxcb-render0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev

os:
  - linux
  - osx

rust:
  - nightly
  - beta
  - stable

script:
  - cargo build
  - cargo build --release
  - cargo test
