language: rust
dist: bionic
osx_image: xcode11
cache: cargo

notifications:
  email: false

addons:
  apt:
    update: true
    packages:
      - xorg-dev

os:
  - linux
  - osx

rust:
  - nightly
  - beta
  - stable

script:
  - cargo build
  - cargo build --release
  - cargo test
