[package]
name = "noa_editorconfig"
version = "0.0.0"
authors = ["Seiya Nuta <nuta@seiya.me>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
log = "0"

[dev-dependencies]
pretty_assertions = "1"
